<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>All detail books</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>aacca845-b75f-4133-aa83-2b9c938930f4</testSuiteGuid>
   <testCaseLink>
      <guid>5d79327c-67ff-4d57-bf13-28e0e0f908aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>52d3a4d3-66da-4d24-a20a-776bbb27a0e0</id>
         <masked>false</masked>
         <name>index</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Visible detail books</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f8eca2a1-8c8b-485e-b69b-26e6b44fb796</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Book-index</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f8eca2a1-8c8b-485e-b69b-26e6b44fb796</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>index</value>
         <variableId>52d3a4d3-66da-4d24-a20a-776bbb27a0e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f8eca2a1-8c8b-485e-b69b-26e6b44fb796</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>title</value>
         <variableId>5247fbdb-ab21-4ba9-bf38-c72395a2f58e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f8eca2a1-8c8b-485e-b69b-26e6b44fb796</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>author</value>
         <variableId>90f43e6d-4a2f-49e3-93e7-a78cff01b9c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f8eca2a1-8c8b-485e-b69b-26e6b44fb796</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>price</value>
         <variableId>7fef12c7-65ee-4e78-a91b-c0aea7cfcbf2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d305d3fc-e385-4176-acf0-49ac2793b9d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search by title book</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f46b4ca4-8504-49a5-a387-bde9d0bd9f34</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Book-index</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f46b4ca4-8504-49a5-a387-bde9d0bd9f34</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>index</value>
         <variableId>bbddd5e3-267e-40c7-bb69-fc4d842e5f60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f46b4ca4-8504-49a5-a387-bde9d0bd9f34</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>title</value>
         <variableId>7c57eed9-cf34-4045-b6b5-a55e033306e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>312c9796-22cb-4137-bf8e-2bec8feb6048</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search by author book</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>39490ca6-1d6c-4bb0-8cae-ef6052ac0520</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Book-index</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>39490ca6-1d6c-4bb0-8cae-ef6052ac0520</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>index</value>
         <variableId>48300d3a-b67e-4556-b8f3-5c3b01524f71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>39490ca6-1d6c-4bb0-8cae-ef6052ac0520</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>author</value>
         <variableId>609e859c-ee34-4efa-bf09-48fd17640256</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95814b9c-860c-4be7-86a5-0f537ff66ac2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Search by price book</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6bf6fbce-ff55-4e77-b104-e99326176c2c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Book-index</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6bf6fbce-ff55-4e77-b104-e99326176c2c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>index</value>
         <variableId>10915d28-be33-4c6e-951c-42a976584749</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6bf6fbce-ff55-4e77-b104-e99326176c2c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>price</value>
         <variableId>8f5ff943-0214-4a09-bbff-8825720c8c7e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
